name: Build & Deploy

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Chores/engineering/build/**"
      - "Chores/sgmodule/**"
      - "Chores/ruleset/**"
      - "Dial/**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
