name: Merge sgmodule files with merged sections

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '7,32,57 * * * *' 

jobs:
  merge_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run merge script
        run: npm run merge

      - name: Check output directory
        run: |
          mkdir -p Chores/sgmodule
          mkdir -p Chores/ruleset
          mkdir -p Surge/Module
          mkdir -p Surge/Ruleset

      - name: Copy all sgmodules to Surge/Module
        run: |
          # 复制所有sgmodule文件
          cp Chores/sgmodule/*.sgmodule Surge/Module/
          # 确保文件权限正确
          chmod 644 Surge/Module/*.sgmodule

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Chores/sgmodule/All-in-One-2.x.sgmodule Chores/ruleset/reject.list Surge/Module/*.sgmodule
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update merged All-in-One-2.x.sgmodule and reject list"
            git push
          fi

      - name: Trigger Deploy Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy

        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
